### ISSUE TITLE
Solarized syntax highlight

### ISSUE THREAD

**Issue by MarcoDeBortoli** [poole/lanyon#100]
I'm trying to get the syntax highlighting work with rouge and the solarized theme but without success. 
Is there something specific within lanyon that prevents me to do so?

I generated the new `syntax.css` file with the following command:

```bash
$ bundle exec rougify style base16.solarized.dark > css/syntax.css
```
This is the post:

```markdown
---
layout: post
title: Hello World
---
### Hello world

{% highlight php %}
<?php

echo 'Hello world!';

{% endhighlight %}
```

And this `_config.yml`
```yaml
# Site settings
title: Title here
description: Description here
author:
  name: Name here
  url: URL here
  email: me@email.com
baseurl: /
timezone: Europe/London
animated: false
show_related_posts: false
 
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_permalinks: true
paginate: 5
sass:
  compressed: true
exclude: [bin, .idea, .bundle, Gemfile*]
 
# Custom vars
version: 1.0.0
```

Still I don't get a solarized version of my code. Am I missing something?

Thanks.

**Comment by nicolasmccurdy** [comment]
Are you sure the CSS file is loaded properly? Try opening the page in your web browser, opening the web console, and reloading. Look for any 404s. Also, check to see if your css directory is in your public directory.

**Comment by MarcoDeBortoli** [comment]
@nicolasmccurdy yes, everything is fine for what I can see.
Apparently the only way I found so far to make this work is as following:

1. Change the `_config.yml` to look like the following:

```yaml
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
```
Instead of just
```yaml
markdown: kramdown
highlighter: rouge
```

2. Change the post code to use git like syntax like following:

```markdown
    ---
    layout: post
    title: Hello World
    ---
    ### Hello world

    ```php
    <?php

    echo 'Hello world!';
    ```
```
Any idea why that would be the case?
