### ISSUE TITLE
Jekyll serve creates wrong local post links after base_url change

### ISSUE THREAD

**Issue by funkenstrahlen** [poole/lanyon#140]
Hey,

I just merged the new changes of this project into my fork. This includes the changes made to the base_url handling with the slash.

I have base_url set to '' (empty string) in my config.yml. When I run `jekyll serve` to test the site locally, I can only access the index site. When I click on a post it links to `http://blog/2015/09/21/homebrew-paketliste-sichern/` instead of `http://localhost:4000/blog/2015/09/21/homebrew-paketliste-sichern/`.

Why does this happen? Should base_url in config.yml be '/' like before? When I do this, this does not fix the problem. I even makes it worse, because CSS does not load any more...

This is the part in index.html which generates the links to the posts:

``` html
      <a href="{{ site.baseurl }}/{{ post.url }}">
        {{ post.title }}
      </a>
```

Before merging it was just

``` html
      <a href="{{ post.url }}">
        {{ post.title }}
      </a>
```

Maybe this part of `config.yml` is the problem:

``` yml
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# /blog/:year/:month/:day/:title/
permalink:           /blog/:year/:month/:day/:title/
relative_permalinks: true
```

However changing it to 

``` yml
permalink:           blog/:year/:month/:day/:title/
```

did not make any difference.
