### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by unnikked** [poole/lanyon#153]
Hi, first of all thank you for this awesome theme. 

I don't know if it's supported but images seems to be unresponsive, check [here](https://unnikked.tk/nuovo-workflow-stackedit/) for an example. 

It's possibile to apply a class to make them responsive ? 

Thank you :smiley:

**Comment by nicolasmccurdy** [comment]
That's odd, it seems like the images should be responsive by default based on [poole.css line 230](https://github.com/poole/lanyon/blob/1c83287f1c389e85f48a409fe3a2e8db0b1964b3/public/css/poole.css#L230).

```css
img {
  display: block;
  max-width: 100%;
  margin: 0 0 1rem;
  border-radius: 5px;
}
```
